name: CI
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Install project dependencies
        uses: docker://dataformco/dataform:1.6.11
        with:
          args: install
      - name: Run dataform compile
        uses: docker://dataformco/dataform:1.6.11
        with:
          args: compile
 
  merge_to_main:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
        with:
          ref: 'demo_dataform'  # Change 'main' to your main branch name
      - name: Merge changes from the feature branch
        run: |
          git merge ${{ github.event.before }}  # Assumes the commit hash of the last commit in the pull request
      - name: Push changes to main branch
        run: |
          git push origin main
